# These are supported funding model platforms

liberapay: thejenja # Replace with a single Liberapay username
custom: ['https://www.donationalerts.com/r/thejenja', 'https://yoomoney.ru/to/410019209648036']
